version: "3.3"
services:
  full_node:
    container_name: full_node
    image: da:poc3 
    tmpfs: /tmp
    volumes:
      - full_node-state:/da/state
      - ./volume/stage/customSpec.json:/da/chain_spec.json:ro
    ports:
      - 9933:9933
      - 9944:9944
      - 30333:30333
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    command: 
      --chain /da/chain_spec.json
      --base-path /da/state
      --name MATIC_FULLNODE
      --keystore-path /da/keystore
      --bootnodes /ip4/54.160.87.220/tcp/30333/p2p/12D3KooWEyoppNCUx8Yx66oV9fJnriXwCcXwDDUA2kj6vnc6iDEp
      --execution Native
      --in-peers 10 
      --out-peers 10
      --port 30333 
      --ws-port 9944
      --ws-external
      --rpc-port 9933
      --rpc-external
      --rpc-cors all

  dapp:
    container_name: dapp 
    build:
      context: ./images/dapp
    image: da-app:master
    environment:
      - WS_URL=wss://polygon-da-explorer.matic.today/ws

  proxy:
    container_name: proxy
    image: kong:2.6.0-alpine
    env_file: env/proxy.env
    depends_on:
      - full_node
      - dapp
    volumes:
      - ./volume/proxy/certs/:/proxy/certs:ro
      - ./volume/proxy/kong.yml:/proxy/kong.yml:ro
    ports:
      - 443:8443
      - 80:8000

volumes:
  full_node-state:

# vim: ts=2:et
