version: "3.3"
services:
  full_node:
    container_name: full_node
    image: da:mat-3347
    tmpfs: /tmp
    volumes:
      - full_node-state:/da/state
    ports:
      - 9933:9933
      - 9944:9944
      - 30333:30333
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    command: 
      --chain /da/genesis/testnet.chain.spec.raw.json
      --base-path /da/state
      --name MATIC_FULLNODE
      --keystore-path /da/keystore
      --bootnodes /ip4/54.160.87.220/tcp/30333/p2p/12D3KooWK1NcYjwpyRUYVG9tjp7X2iGbrQxNVafC5hJU9mggYTgv
      --execution Native
      --in-peers 10 
      --out-peers 10
      --port 30333 
      --ws-port 9944
      --ws-external
      --rpc-port 9933
      --rpc-external
      --rpc-cors all

  dapp:
    container_name: dapp 
    image: dapp:asdr
    environment:
      - WS_URL=wss://polygon-da-explorer.matic.today/ws

  # Redis is used to store certificates
  redis:
    container_name: redis
    image:  redis:6-alpine
    command: "redis-server --save 60 1"
    volumes:
      - ./volume/redis/data:/data

  proxy:
    container_name: proxy
    image: kong:2.6.0-alpine
    env_file: env/proxy.env
    depends_on:
      - full_node
      - dapp
      - redis
    volumes:
      - ./volume/proxy/kong.yml:/proxy/kong.yml:ro
    ports:
      - 443:8443
      - 80:8000

volumes:
  full_node-state:

# vim: ts=2:et
