version: "3.3"
services:
  validator1:
    container_name: validator1 
    build:
      context: ./images/node
      args:
        - BRANCH=da-poc-upgrade-3.0
    image: da:poc3 
    tmpfs: /tmp
    volumes:
      - validator1-state:/da/state
      - ./volume/stage/customSpec.json:/da/chain_spec.json:ro
      - ./volume/stage/validator1/node.private.key:/da/node.key:ro
      - ./volume/stage/validator1/keystore:/da/keystore
    #ports:
      #- 9944:9944
      #- 30333:30333
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    command: 
      --validator
      --chain /da/chain_spec.json
      --base-path /da/state
      --name MATIC_VALIDATOR_1
      --node-key-file /da/node.key
      --keystore-path /da/keystore
      --execution Native
      --in-peers 10 
      --out-peers 10
      --port 30333 
      --no-prometheus
      --rpc-cors all
      --unsafe-ws-external
      --rpc-methods=Unsafe
      --ws-port 9944
      --rpc-port 9933

  validator2:
    container_name: validator2
    image: da:poc3 
    tmpfs: /tmp
    volumes:
      - validator2-state:/da/state
      - ./volume/stage/customSpec.json:/da/chain_spec.json:ro
      - ./volume/stage/validator2/node.private.key:/da/node.key:ro
      - ./volume/stage/validator2/keystore:/da/keystore
    #ports:
      #- 9944:9944
      #- 30333:30333
    depends_on:
      - validator1
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    command: 
      --validator
      --chain /da/chain_spec.json
      --base-path /da/state
      --name MATIC_VALIDATOR_2
      --node-key-file /da/node.key
      --keystore-path /da/keystore
      --bootnodes /dns4/validator1/tcp/30333/p2p/12D3KooWHxePyMWRmrwWmxaFmHHLs5qKmZPhAP5puJ2ZwMQMfAfB
      --execution Native
      --in-peers 10 
      --out-peers 10
      --port 30333 
      --no-prometheus
      --rpc-cors all
      --unsafe-ws-external
      --rpc-methods=Unsafe
      --ws-port 9944
      --rpc-port 9933

  validator3:
    container_name: validator3
    image: da:poc3 
    tmpfs: /tmp
    volumes:
      - validator3-state:/da/state
      - ./volume/stage/customSpec.json:/da/chain_spec.json:ro
      - ./volume/stage/validator3/node.private.key:/da/node.key:ro
      - ./volume/stage/validator3/keystore:/da/keystore
    #ports:
      #- 9944:9944
      #- 30333:30333
    depends_on:
      - validator1
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    command: 
      --validator
      --chain /da/chain_spec.json
      --base-path /da/state
      --name MATIC_VALIDATOR_3
      --node-key-file /da/node.key
      --keystore-path /da/keystore
      --bootnodes /dns4/validator1/tcp/30333/p2p/12D3KooWHxePyMWRmrwWmxaFmHHLs5qKmZPhAP5puJ2ZwMQMfAfB
      --execution Native
      --in-peers 10 
      --out-peers 10
      --port 30333 
      --no-prometheus
      --rpc-cors all
      --unsafe-rpc-external
      --rpc-methods=Unsafe
      --ws-port 9944
      --rpc-port 9933

volumes:
  validator1-state:
  validator2-state:
  validator3-state:

# vim: ts=2:et
