version: "3.3"
services:
  validator3:
    container_name: validator3
    image: da:poc3 
    tmpfs: /tmp
    volumes:
      - validator3-state:/da/state
      - ./volume/stage/customSpec.json:/da/chain_spec.json:ro
      - ./volume/stage/validator3/node.private.key:/da/node.key:ro
      - ./volume/stage/validator3/keystore:/da/keystore
    ports:
      - 9933:9933
      - 9944:9944
      - 30333:30333
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    command: 
      --validator
      --chain /da/chain_spec.json
      --base-path /da/state
      --name MATIC_VALIDATOR_3
      --node-key-file /da/node.key
      --keystore-path /da/keystore
      --bootnodes /ip4/54.160.87.220/tcp/30333/p2p/12D3KooWRfAFixXQ2VQ6yNPuoc3UTP8CjN4z8kw1eU5fnuQpPygu
      --bootnodes /ip4/3.218.2.152/tcp/30333/p2p/12D3KooWQtxig5HukFDwQzshGWgQEZAqGqdCN7AQBW7cQRJWCyxL
      --execution Native
      --in-peers 10 
      --out-peers 10
      --port 30333 
      --rpc-cors all
      --ws-port 9944
      --rpc-port 9933

volumes:
  validator3-state:

# vim: ts=2:et
